---
- name: set fact for instack file
  set_fact:
    instackenv_file: "{{ instackenv_file|default('{{ ansible_user_dir }}/instackenv.json', true) }}"

- name: check instackenv file available
  stat:
      path: "{{ instackenv_file }}"
  register: st

- name: Download instackenv.json
  get_url:
      url: "{{ alias.lab_url }}/cloud/{{ cloud_name }}_instackenv.json"
      dest: "{{ instackenv_file }}"
      mode: '0644'
      force: yes
  when: st.stat.exists == False and lab_name == "alias"

- name: Download instackenv.json
  get_url:
      url: "{{ scale.lab_url }}/cloud/{{ cloud_name }}_instackenv.json"
      dest: "{{ instackenv_file }}"
      mode: '0644'
      force: yes
  when: st.stat.exists == False and lab_name == "scale"

- name: set facts
  set_fact:
    instackenv_content: "{{ instackenv_content }}"
    undercloud_hostname: "{{ undercloud_hostname|default(instackenv_content.nodes[0].pm_addr | replace('mgmt-','') | replace('-drac', '')) }}"
    overcloud_instackenv_path: "{{ ansible_user_dir }}/overcloud_instackenv.json"
  vars:
      instackenv_content: "{{ lookup('file', '{{ instackenv_file }}') | from_json }}"

- name: set overcloud_instackenv content
  set_fact:
      instackenv_content: |
          {% set a=instackenv_content.pop('nodes') %}
          {{ instackenv_content | combine({'nodes': a|difference([a[0]])}, recursive=True) }}

- name: create overcloud_instackenv.json file
  copy:
      dest: "{{ overcloud_instackenv_path }}"
      content: "{{ instackenv_content }}"

- name: replace instackenv_content with original data
  set_fact:
      instackenv_content: "{{ lookup('file', '{{ instackenv_file }}') | from_json }}"
